name: Build and Deploy React App to Cloudfront
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: project-2022-23t2-g1-t4-s3
      DIST: build
      REGION: us-east-1
      DIST_ID: E2LCGEZXWMDUCE

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Build React App
      run: npm install && npm run build

    - name: Deploy app build to S3 bucket
      run: aws s3 sync ./build/ s3://project-2022-23t2-g1-t4-s3 --delete

    - name: Copy files to production website with the AWS CLI
      run:
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"

